### ISSUE TITLE
demos link error

### ISSUE THREAD

**Issue by wenshengsheng2020** [Project-10/OpenRT#11]
CMakeFiles/Demo_AreaLight.dir/Demo_AreaLight.cpp.o: In function `main':
Demo AreaLight.cpp:(.text+0x833): undefined reference to `rt::CSolid::CSolid(std::shared_ptr<rt::IShader>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
Demo AreaLight.cpp:(.text+0xe20): undefined reference to `rt::CSolid::transform(cv::Mat const&)'
Demo AreaLight.cpp:(.text+0x129c): undefined reference to `rt::CScene::render(std::shared_ptr<rt::CSampler>) const'
Demo AreaLight.cpp:(.text+0x12c4): undefined reference to `rt::CScene::renderDepth() const'
CMakeFiles/Demo_AreaLight.dir/Demo_AreaLight.cpp.o: In function `rt::CCameraPerspective::CCameraPerspective(cv::Size_<int>, cv::Vec<float, 3> const&, cv::Vec<float, 3> const&, cv::Vec<float, 3> const&, float)':
Demo AreaLight.cpp:(.text._ZN2rt18CCameraPerspectiveC2EN2cv5Size_IiEERKNS1_3VecIfLi3EEES7_S7_f[_ZN2rt18CCameraPerspectiveC5EN2cv5Size_IiEERKNS1_3VecIfLi3EEES7_S7_f]+0x5a): undefined reference to `vtable for rt::CCameraPerspective'
CMakeFiles/Demo_AreaLight.dir/Demo_AreaLight.cpp.o: In function `rt::CLightOmni::CLightOmni(cv::Vec<float, 3> const&, cv::Vec<float, 3> const&, bool)':
Demo AreaLight.cpp:(.text._ZN2rt10CLightOmniC2ERKN2cv3VecIfLi3EEES5_b[_ZN2rt10CLightOmniC5ERKN2cv3VecIfLi3EEES5_b]+0x2f): undefined reference to `vtable for rt::CLightOmni'
CMakeFiles/Demo_AreaLight.dir/Demo_AreaLight.cpp.o: In function `rt::CPrimSphere::CPrimSphere(std::shared_ptr<rt::IShader>, cv::Vec<float, 3>, float)':
Demo AreaLight.cpp:(.text._ZN2rt11CPrimSphereC2ESt10shared_ptrINS_7IShaderEEN2cv3VecIfLi3EEEf[_ZN2rt11CPrimSphereC5ESt10shared_ptrINS_7IShaderEEN2cv3VecIfLi3EEEf]+0x5e): undefined reference to `vtable for rt::CPrimSphere'
CMakeFiles/Demo_AreaLight.dir/Demo_AreaLight.cpp.o: In function `rt::CPrimPlane::CPrimPlane(std::shared_ptr<rt::IShader>, cv::Vec<float, 3>, cv::Vec<float, 3>)':
Demo AreaLight.cpp:(.text._ZN2rt10CPrimPlaneC2ESt10shared_ptrINS_7IShaderEEN2cv3VecIfLi3EEES6_[_ZN2rt10CPrimPlaneC5ESt10shared_ptrINS_7IShaderEEN2cv3VecIfLi3EEES6_]+0x5d): undefined reference to `vtable for rt::CPrimPlane'
CMakeFiles/Demo_AreaLight.dir/Demo_AreaLight.cpp.o: In function `rt::CPrimTriangle::CPrimTriangle(std::shared_ptr<rt::IShader>, cv::Vec<float, 3> const&, cv::Vec<float, 3> const&, cv::Vec<float, 3> const&, cv::Vec<float, 2> const&, cv::Vec<float, 2> const&, cv::Vec<float, 2> const&)':
Demo AreaLight.cpp:(.text._ZN2rt13CPrimTriangleC2ESt10shared_ptrINS_7IShaderEERKN2cv3VecIfLi3EEES8_S8_RKNS5_IfLi2EEESB_SB_[_ZN2rt13CPrimTriangleC5ESt10shared_ptrINS_7IShaderEERKN2cv3VecIfLi3EEES8_S8_RKNS5_IfLi2EEESB_SB_]+0x75): undefined reference to `vtable for rt::CPrimTriangle'
CMakeFiles/Demo_AreaLight.dir/Demo_AreaLight.cpp.o: In function `rt::CPrimTriangle::if_intersect(rt::Ray const&) const':
Demo AreaLight.cpp:(.text._ZNK2rt13CPrimTriangle12if_intersectERKNS_3RayE[_ZNK2rt13CPrimTriangle12if_intersectERKNS_3RayE]+0x32): undefined reference to `rt::CPrimTriangle::MoellerTrumbore(rt::Ray const&) const'
CMakeFiles/Demo_AreaLight.dir/Demo_AreaLight.cpp.o: In function `rt::CTransform::scale(float) const':
Demo AreaLight.cpp:(.text._ZNK2rt10CTransform5scaleEf[_ZNK2rt10CTransform5scaleEf]+0x4e): undefined reference to `rt::CTransform::scale(cv::Vec<float, 3> const&) const'
CMakeFiles/Demo_AreaLight.dir/Demo_AreaLight.cpp.o: In function `rt::CPrimTriangle::~CPrimTriangle()':
Demo AreaLight.cpp:(.text._ZN2rt13CPrimTriangleD2Ev[_ZN2rt13CPrimTriangleD5Ev]+0xf): undefined reference to `vtable for rt::CPrimTriangle'
CMakeFiles/Demo_AreaLight.dir/Demo_AreaLight.cpp.o: In function `rt::CPrimTriangleSmooth::transform(cv::Mat const&)':

**Comment by ereator** [comment]
Please try to call CMake using the line:
`cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local`
If it will not fix the problem, please provide additional information as your Operating System, and compiler.

**Comment by wenshengsheng2020** [comment]
that's great,  thanks very much
