### ISSUE TITLE
Wrong normal orientation in resulting geometry composites

### ISSUE THREAD

**Issue by ereator** [Project-10/OpenRT#34]
Hi @otmanesabir 
In class CCompositeGeometry in the method CCompositeGeometry::computeDifference :
https://github.com/Project-10/OpenRT/blob/0d7a54c40f2d43647af62a841a91fbea4049a3e9/modules/core/CompositeGeometry.cpp#L292-L307
for the cases when the camera is inside the composite (_i.e._ when intersection with prim B is closer than intersection with prim A), the normals for the difference area are directed towards the camera. But as the camera is inside, all the normals should be directed outwards the camera. To check the bug, one may render the scene:
```
std::shared_ptr<CScene> buildSceneTest(const Vec3f& bgColor, const Size resolution)
{
	auto pScene = std::make_shared<CScene>(bgColor);
	
	// shaders
	auto pShader = std::make_shared<CShaderFlat>(Vec3f(1, 1, 1));
	
	// geometry
	ptr_prim_t largeSphere = std::make_shared<CPrimSphere>(pShader, Vec3f(0, 0, 0), 5.0f);
	ptr_prim_t smallSphere = std::make_shared<CPrimSphere>(pShader, Vec3f(0, 0, -5), 1.0f);
	ptr_prim_t composite 	 = std::make_shared<CCompositeGeometry>(largeSphere, smallSphere, BoolOp::Difference);
	
	//pScene->add(largeSphere);
	//pScene->add(smallSphere);
	pScene->add(composite);
	
	// Light
	pScene->add(std::make_shared<CLightOmni>(Vec3f::all(1e3), Vec3f(0, 0, 0), true));
	
	// camera
	pScene->add(std::make_shared<CCameraPerspective>(resolution, Vec3f(0, 0, 0), Vec3f(0, 0, -1), Vec3f(0, 1, 0), 45.0f));
	
	return pScene;
} 
```

**Comment by otmanesabir** [comment]
Hi @ereator 

Thank you for raising the issue 👍  
Apologies for the delayed response. I somehow never received a notif for this.
Seems like a case where the normal should be flipped. I will have a look at this and fix it ASAP.
Could you maybe assign me this issue here on GitHub?

**Comment by ereator** [comment]
Hi @otmanesabir 
Thanks for the answer. Meanwhile I have fixed the bug. 
I believe there was a typo: When substract B from A, we need to invert the normals all the time only for B and never for A. So I just moved lines 297 - 300 to the second part of the condition checking - just after the line 304.
I also done a small code simplification.

Next, I plan to get rid of the dummy primitive by introducing a method `void IPrim::flipNormal(void)`.

**Comment by otmanesabir** [comment]
thank you for taking it on and fixing it in the commit! it looks good to me :)

Meanwhile, I'd like to take on adding the mentioned method if possible - I can open a PR for it the upcoming weekend as it should be quite straightforward :)

**Comment by ereator** [comment]
@otmanesabir, thank you so much your wish to help. I have created an issue #35 as a _feture request / enhancement_, where we can discuss flipping normals.
