### ISSUE TITLE
Create a simpler constructor for CSolidQuad 

### ISSUE THREAD

**Issue by otmanesabir** [Project-10/OpenRT#40]
Given that we typically use the CSolidQuad to generate floor or similar items, I think it would be much friendlier to introduce a constructor that can generate a CSolidQuad from an origin point and length/width parameters. We can also introduce angles for inclination but I also believe that can be achieved with transformation.

@ereator if you think this minor modification can be helpful then I would be happy to quickly work on this :)

**Comment by ereator** [comment]
Hi @otmanesabir 
Thank you for proposing this enhancement. CSolidQuad has the following auxiliary constructor:
```
/**
	* @brief Constructor
	* @param pShader Pointer to the shader to be applied for the solid
	* @param origin The center of the quadrilateral
	* @param normal The normal of the quadrilateral
	* @param right The right vector of the quadrilateral
	* @param r The size of the quadrilateral
	*/
DllExport CSolidQuad(const ptr_shader_t pShader, const Vec3f& origin = Vec3f::all(0), const Vec3f& normal = Vec3f(0, 1, 0), const Vec3f& right = Vec3f(1, 0, 0), float r = 1);
```
The angles are implicitly can be given by the right vector. Is that smth similar to what you propose to use ?

**Comment by otmanesabir** [comment]
Ah! the idea of a vector is really nice for orientation, but basically, my idea was to use an origin point, a vector for orientation a length, and an optional width parameter
/**
	* @brief Constructor
	* @param pShader Pointer to the shader to be applied for the solid
	* @param origin The center of the quadrilateral
	* @param normal The normal of the quadrilateral
	* @param length The length of the quadrilateral
	* @param width The width of the quadrilateral (if null, width = length)
	*/

**Comment by ereator** [comment]
Sure, feel free to modify it 👍

**Comment by otmanesabir** [comment]
@ereator apologies for the delay on this.

I took a deeper look into this and realized that while it is 'feasible' this might not be geometrically correct. Basically, there are infinite quads that we can generate from a center point and a normal vector (take any quad and rotate it around this vector through this center and all of them are solutions).

My initial idea was closer to how we can generate a 'finite plane'. We can still technically do that; however, this wouldn't be a sound definition of a quad.

I will close this for now but can reopen if any strong points from your side
